"""s

Revision ID: 0bce2585d331
Revises: 82c89f904d41
Create Date: 2025-09-04 12:21:29.110323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bce2585d331'
down_revision: Union[str, None] = '82c89f904d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_applications', sa.Column('card_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_applications', 'card_name')
    # ### end Alembic commands ###
